### ISSUE TITLE
Cannot run plugin on windows

### ISSUE THREAD

**Issue by amagnus** [tagomoris/fluent-plugin-secure-forward#12]
I'm running fluentd 0.10.46 from the windows branch:
https://github.com/fluent/fluentd/archive/windows.zip

OS is Windows Server 2012 R2.

Getting this error when starting fluentd:

```
2014-12-23 23:24:47 +0000 [error]: unexpected error error_class=Errno::ENOENT error=#<Errno::ENOENT: No such file or directory - /dev/urandom>
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluent-plugin-secure-forward-0.2.4/lib/fluent/plugin/out_secure_forward.rb:121:in `read'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluent-plugin-secure-forward-0.2.4/lib/fluent/plugin/out_secure_forward.rb:121:in `start'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/plugin/out_copy.rb:50:in `block in start'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/plugin/out_copy.rb:49:in `each'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/plugin/out_copy.rb:49:in `start'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/match.rb:40:in `start'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/engine.rb:260:in `block in start'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/engine.rb:259:in `each'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/engine.rb:259:in `start'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/engine.rb:206:in `run'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/supervisor.rb:458:in `run_engine'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/supervisor.rb:120:in `block in start'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/supervisor.rb:251:in `call'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/supervisor.rb:251:in `main_process'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/supervisor.rb:214:in `supervise'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/supervisor.rb:108:in `start'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/command/fluentd.rb:225:in `<top (required)>'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/bin/fluentd:6:in `<top (required)>'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/bin/fluentd:23:in `load'
  2014-12-23 23:24:47 +0000 [error]: C:/Ruby193/bin/fluentd:23:in `<main>'
```

Here is my config file:

```
<source>
  type tail
  path C:\fluentd\hello.txt
  tag jvm
  format /^(?<time>\d\d\d\d-(\d)?\d-(\d)?\d \d\d:\d\d:\d\d)[ ]{1,3}(?<message>.*)$/
  time_format %Y-%m-%d %H:%M:%S
</source>

<match jvm.**>
  type copy
  <store>
    type secure_forward
    shared_key    **************
    self_hostname    ${hostname}
    keepalive 120

    <server>
      host ******************
    </server>

    buffer_type file
    buffer_path C:\fluentd\myapp-buffer
    retry_limit 50
    flush_interval 20s
  </store>
</match>
```

**Comment by tagomoris** [comment]
Fixed at 3a48c65acd1efeba4fbc763c1bdb40ee2d78437a and released as v0.2.5.
Thank you for reporting!
