### ISSUE TITLE
can't modify frozen String

### ISSUE THREAD

**Issue by slava-vishnyakov** [tagomoris/fluent-plugin-secure-forward#20]
I'm trying to run the plugin on FreeBSD and get this error:

```sh
2015-06-15 20:41:52 +0300 [error]: unexpected error error="can't modify frozen String"
  2015-06-15 20:41:52 +0300 [error]: /usr/local/lib/ruby/gems/2.1/gems/fluent-plugin-secure-forward-0.3.2/lib/fluent/plugin/output_node.rb:319:in `feed_each'
  2015-06-15 20:41:52 +0300 [error]: /usr/local/lib/ruby/gems/2.1/gems/fluent-plugin-secure-forward-0.3.2/lib/fluent/plugin/output_node.rb:319:in `block in connect'
  2015-06-15 20:41:52 +0300 [error]: /usr/local/lib/ruby/gems/2.1/gems/fluent-plugin-secure-forward-0.3.2/lib/fluent/plugin/output_node.rb:310:in `loop'
  2015-06-15 20:41:52 +0300 [error]: /usr/local/lib/ruby/gems/2.1/gems/fluent-plugin-secure-forward-0.3.2/lib/fluent/plugin/output_node.rb:310:in `connect'
```

The same config on Ubuntu works fine

```sh
<match *.**>
  type secure_forward
  shared_key ......
  self_hostname ${hostname}
  secure no

  flush_interval 1s
  <server>
    name ...
    host ...
    port ...
    weight 60
  </server>
</match>
```

**Comment by slava-vishnyakov** [comment]
Just in case: the installation on FreeBSD is done like this
```sh
pkg install rubygem-fluentd 
/usr/local/bin/fluent-gem install fluent-plugin-secure-forward
```

The config file is `/usr/local/etc/fluentd/fluent.conf` and command to test is 
```sh
/usr/local/bin/fluentd -c /usr/local/etc/fluentd/fluent.conf
```

**Comment by repeatedly** [comment]
It seems similar case with this > https://github.com/fluent/fluentd/issues/598
Could you update fluentd to latest version?

**Comment by tagomoris** [comment]
I'll close this at once. Please open another issue for further problems.
