### ISSUE TITLE
uninitialized constant Fluent::Input on fluentd 0.14.1

### ISSUE THREAD

**Issue by JoeOrtiz** [tagomoris/fluent-plugin-secure-forward#40]
Getting this on the new version of fluentd:

```
 adding source type="secure_forward"
 unexpected error error="uninitialized constant Fluent::Input"
 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-secure-forward-0.4.1/lib/fluent/plugin/in_secure_forward.rb:6:in `<module:Fluent>'
 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-secure-forward-0.4.1/lib/fluent/plugin/in_secure_forward.rb:5:in `<top (required)>'
 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/registry.rb:81:in `block in search'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/registry.rb:79:in `each'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/registry.rb:79:in `search'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/registry.rb:42:in `lookup'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/plugin.rb:146:in `new_impl'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/plugin.rb:100:in `new_input'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/root_agent.rb:229:in `add_source'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/root_agent.rb:95:in `block in configure'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/root_agent.rb:92:in `each'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/root_agent.rb:92:in `configure'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/engine.rb:119:in `configure'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/engine.rb:93:in `run_configure'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/supervisor.rb:594:in `run_configure'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/supervisor.rb:389:in `block in run_worker'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/supervisor.rb:527:in `main_process'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/supervisor.rb:385:in `run_worker'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/command/fluentd.rb:271:in `<top (required)>'
 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/bin/fluentd:5:in `<top (required)>'
 /usr/bin/fluentd:23:in `load'
 /usr/bin/fluentd:23:in `<main>'

```

**Comment by tagomoris** [comment]
I've just released v0.4.2, which is fixed for this issue.
Thank you for reporting!
